version: "3"

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
      - "9000:9000"
    #expose:
    #  - 9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopwd
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 256M
